create database cozy;
create table LIST_ITEMS (
 name VARCHAR(200),
 index BIGINT,
 list BIGINT,
 color VARCHAR(50),
 decorator VARCHAR(50)
);

ALTER TABLE LIST_ITEMS ALTER COLUMN name SET NOT NULL;
ALTER TABLE LIST_ITEMS ALTER COLUMN index SET NOT NULL;
ALTER TABLE LIST_ITEMS ALTER COLUMN list SET NOT NULL;
ALTER TABLE LIST_ITEMS ALTER COLUMN color SET NOT NULL;
ALTER TABLE LIST_ITEMS ALTER COLUMN decorator SET NOT NULL;

--> server state
--> local state
